// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const GET_LOCATIONS = "GET_LOCATIONS"

// AUTH TYPES
export const GET_USER_PENDING = "GET_USER_PENDING"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

// LOGIN TYPES
export const LOGIN_PENDING = "LOGIN_PENDING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

// LOGIN TYPES
export const LOGOUT_PENDING = "LOGOUT_PENDING"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

// CREATE USER TYPES
export const CREATE_USER_PENDING = "CREATE_USER_PENDING"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

// SELECTING/REMOVING MARKERS
export const SELECT_MARKER = "SELECT_MARKER"
export const REMOVE_MARKER = "REMOVE_MARKER"

// GET LOCATION TYPES
export const GET_LOCATIONS_FAIL = "GET_LOCATIONS_FAIL"
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS"
export const GET_LOCATIONS_PENDING = "GET_LOCATIONS_PENDING"

// GET FRIEND LOCATION TYPES
export const GET_FRIENDS_LOCATIONS_FAIL = "GET_FRIENDS_LOCATIONS_FAIL"
export const GET_FRIENDS_LOCATIONS_SUCCESS = "GET_FRIENDS_LOCATIONS_SUCCESS"
export const GET_FRIENDS_LOCATIONS_PENDING = "GET_FRIENDS_LOCATIONS_PENDING"
